apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "prometheus-optimizer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: prometheus-optimizer
spec:
  schedule: {{ .Values.cronJob.schedule }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: prometheus-optimizer
        spec:
          containers:
            - name: prometheus-optimizer
              image: "{{ .Values.cronJob.image.repository }}:{{ .Values.cronJob.image.tag }}"
              imagePullPolicy: {{ .Values.cronJob.image.pullPolicy }}
              volumeMounts:
                - name: config-volume
                  mountPath: /usr/src/app/config.yaml
                  subPath: config.yaml
          volumes:
            - name: config-volume
              configMap:
                name: {{ .Values.configMap.name }}
          restartPolicy: OnFailure
          serviceAccountName: {{ .Values.serviceAccount.name }}