apiVersion: batch/v1
kind: Job
metadata:
  name: prometheus-optimizer-job
  labels:
    app: prometheus-optimizer
spec:
  template:
    metadata:
      labels:
        app: prometheus-optimizer
    spec:
      containers:
        - name: prometheus-optimizer
          image: ghcr.io/venomseven/prometheus-optimizer:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: config-volume
              mountPath: /usr/src/app/config.yaml
              subPath: config.yaml
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-optimizer-config
      restartPolicy: OnFailure
      serviceAccountName: optimizer-service-account
