apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: optimizer-role
rules:
  - apiGroups: [""]
    resources: ["pods/exec","pods"]
    verbs: ["create","list","get","watch"]

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: optimizer-service-account

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: optimizer-cluster-rolebinding
subjects:
  - kind: ServiceAccount
    name: optimizer-service-account
roleRef:
  kind: ClusterRole
  name: optimizer-role
  apiGroup: rbac.authorization.k8s.io
